---
# Ansible playbook for a LAMP server.
#
# @author Jeff Geerling (2014).

- hosts: lamp
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
     - common
     - geerlingguy.firewall
     - geerlingguy.ntp
     - geerlingguy.mysql
     - geerlingguy.apache
     - geerlingguy.php
     - { role: phpmyadmin, tags: [phpmyadmin] }