---
# Ansible playbook for a LAMP server.
#
# @author Jeff Geerling (2014).

- hosts: all
  gather_facts: yes
  roles:
     - common
     - geerlingguy.firewall
     - geerlingguy.ntp
     - geerlingguy.mysql
     - geerlingguy.apache
     - geerlingguy.php
     - { role: phpmyadmin, tags: [phpmyadmin] }